import type { Metadata } from 'next'
import { site } from '@/lib/site'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: `The terms for using ${site.name}.`,
  alternates: { canonical: '/terms' },
}

export default function TermsPage() {
  return (
    <main className="legal">
      <div className="wrap wrap-narrow">
        <h1>Terms of Service</h1>
        <p>Last updated: October 6, 2026</p>

        <h2>The service</h2>
        <p>
          {site.name} is a Chrome extension that uses AI to draft Upwork proposals and answers to screening questions
          from the job post you are viewing. By installing or using it you agree to these terms.
        </p>

        <h2>Your account</h2>
        <p>
          You sign in with a Google account. You are responsible for activity under your account and for keeping the
          information in your profile accurate.
        </p>

        <h2>Drafts are yours to check</h2>
        <p>
          Proposals are generated by an AI model and can contain mistakes. You are responsible for reviewing every
          draft and for anything you submit to a client. {site.name} never submits a proposal for you and makes no
          promise that a proposal will win a job.
        </p>

        <h2>Upwork</h2>
        <p>
          {site.name} is independent and is not affiliated with or endorsed by Upwork. You are responsible for
          following Upwork’s terms and policies when you use it.
        </p>

        <h2>Plans and payment</h2>
        <ul>
          <li>New accounts get {site.freeProposals} free proposals, once.</li>
          <li>Starter is $9 per month for 30 proposals. Pro is $15 per month for 60 proposals.</li>
          <li>Each Generate or Regenerate uses one proposal. A failed generation is not counted.</li>
          <li>Plans renew monthly until cancelled. Unused proposals do not carry over to the next period.</li>
          <li>
            You can cancel at any time from “Manage subscription” in the extension. Your plan stays active until the
            end of the period already paid for.
          </li>
          <li>Payments are processed by Stripe. If a charge looks wrong, contact us.</li>
        </ul>

        <h2>Fair use</h2>
        <p>
          Do not share an account, resell access, try to get around the usage limits, or use the service to produce
          content that is unlawful or deceptive. We may suspend accounts that do.
        </p>

        <h2>Availability and changes</h2>
        <p>
          The service is provided as is. It depends on Upwork’s page layout and on third-party providers, so it can be
          interrupted. We may change features, prices or these terms; price changes apply from your next billing
          period.
        </p>

        <h2>Contact</h2>
        <p>
          <a href={`mailto:${site.supportEmail}`}>{site.supportEmail}</a>
        </p>
      </div>
    </main>
  )
}
