export const CONTENT_SCRIPT = {
  GENERATE_OPENAI_BID: 'GENERATE_OPENAI_BID',
  GET_SELECTORS: 'GET_SELECTORS',
  GET_TEMPLATE: 'GET_TEMPLATE',
}

export const BACKGROUND_SERVICE_WORKER = {
  GET_OPENAI_RESPONSE: 'GET_OPENAI_RESPONSE',
}

export const MESSAGES = {
  WAIT_FOR_ACTIVE_TAB_LOADS: "WAIT_FOR_ACTIVE_TAB_LOADS"
}
